#!/usr/bin/python3
import socket
import subprocess
import argparse
import sys
import configparser
import os
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
from base64 import b64encode

def encrypt(mess, key):
   obj = AES.new(key, AES.MODE_CBC, 'This is an IV456')
   mess=mess.encode()
   length = 16 - (len(mess) % 16)
   mess += bytes([length])*length
   ciphertext = obj.encrypt(mess)
   return ciphertext

def decrypt(msg, key):
   obj = AES.new(key, AES.MODE_CBC, 'This is an IV456')
   msg1=obj.decrypt(msg)
   msg1 = msg1[:-msg1[-1]]
   return msg1


config = configparser.ConfigParser()
config.read('yottacmd.ini')
yottaconfig = config['YottaDB']
port=yottaconfig['Port']
host=yottaconfig['Host']
Username=yottaconfig['Username']
Password=yottaconfig['Password']
try:
    socket.inet_aton(host)
except socket.error:
    print("Configured host is incorrect")
    sys.exit(1)
s=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((host, int(port)))
s.listen(5)
while True:
   psucc=0
   usucc=0
   clientsocket, address = s.accept()
   print(f"Connection from {address} has been established!")
   key = os.urandom(16)
   key_bytes=b64encode(key).decode('utf-8')
   msg=clientsocket.recv(1024)
   clientsocket.send(bytes(key_bytes, "utf-8"))
   key=key_bytes
   msg=clientsocket.recv(1024) 
   msg1=decrypt(msg, key)
   if (msg1.decode("utf-8") != Username):
       resp="Username is incorrect"
       ciphertext = encrypt(resp, key)
       clientsocket.send(ciphertext)
       clientsocket.close()
   else:
       resp=""
       ciphertext = encrypt(resp, key)
       clientsocket.send(ciphertext)
       usucc=1
   if ( usucc == 1 ):
      msg=clientsocket.recv(1024)
      msg1=decrypt(msg, key)
      if (msg1.decode("utf-8") != Password):
          resp="Password is incorrect"
          ciphertext = encrypt(resp, key)
          clientsocket.send(ciphertext)
          clientsocket.close()
      else:
          resp=" "
          ciphertext = encrypt(resp, key)
          clientsocket.send(ciphertext)
          psucc=1
   if ( usucc==1 and psucc==1 ):
      msg=clientsocket.recv(1024)
      msg1=decrypt(msg, key)
      if ( msg1.decode("utf-8") == "" ):
         cmd="yottacmd command --help"
      else: 
         cmd="yottacmd " + msg1.decode("utf-8")
      process = subprocess.Popen(cmd,
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE,
                              shell=True)
      result, err = process.communicate()
      print(result)
      if (result.decode("utf-8")!=""):
         reslen=str(len(result))
         ciphertext = encrypt(reslen, key)
         clientsocket.send(ciphertext)
         msg=clientsocket.recv(1024)
         msg1=decrypt(msg, key)
         ciphertext = encrypt(result.decode("utf-8"), key)
         clientsocket.send(ciphertext)
      else:
         errlen=str(len(err))
         ciphertext = encrypt(errlen, key)
         clientsocket.send(ciphertext)
         msg=clientsocket.recv(1024)
         msg1=decrypt(msg, key)
         ciphertext = encrypt(err.decode("utf-8"), key)
         clientsocket.send(ciphertext)
